#!/bin/bash
# docker/init-env.sh — Generates project-root .env with random secrets if missing.
# Runs as a one-shot container (env-setup) before any service that needs .env.
# Idempotent: an existing .env is never overwritten.

set -e

ENV_FILE="/host/.env"

if [ -f "$ENV_FILE" ]; then
  echo "Found existing .env at $ENV_FILE — skipping generation"
  exit 0
fi

echo "Generating .env with random secrets at $ENV_FILE..."

# Generate random secrets (try openssl first, fall back to python3).
if command -v openssl &> /dev/null; then
  POSTGRES_PASSWORD=$(openssl rand -hex 16)
  LITELLM_MASTER_KEY="sk-litellm-$(openssl rand -hex 24)"
  SESSION_SECRET=$(openssl rand -hex 16)
  SECRET_ENCRYPTION_KEY=$(openssl rand -base64 32 | tr -d '\n')
elif command -v python3 &> /dev/null; then
  POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_hex(16))")
  LITELLM_MASTER_KEY="sk-litellm-$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")"
  SESSION_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(16))")
  SECRET_ENCRYPTION_KEY=$(python3 -c "import secrets, base64; print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())")
else
  echo "ERROR: Neither openssl nor python3 available — cannot generate secrets"
  exit 1
fi

cat > "$ENV_FILE" << EOF
# LLM Gateway Environment Variables
# Auto-generated by init-env container on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Modify as needed — see docker/.env.example for reference.

NVIDIA_API_KEY=
GROQ_API_KEY=
CEREBRAS_API_KEY=
OPENROUTER_API_KEY=

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://llm_gateway:${POSTGRES_PASSWORD}@postgres:5432/llm_gateway
GATEWAY_DB_URL=postgresql://llm_gateway:${POSTGRES_PASSWORD}@postgres:5432/llm_gateway
REDIS_URL=redis://redis:6379/0
GATEWAY_REDIS_URL=redis://redis:6379/0

SESSION_SECRET=${SESSION_SECRET}
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}

# Fernet key for encrypting provider API keys at rest (P1.2.1). Must be a
# base64 32-byte key. If lost, stored credentials cannot be decrypted.
SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
EOF

chmod 600 "$ENV_FILE"
echo "Generated .env at $ENV_FILE with mode 600"
echo ""
echo "Next: cd docker && docker compose --profile full up -d"
exit 0
