"""
wizard/install_linux.py — systemd unit installer (Phase 4 deliverable 4).

Writes a user-level systemd unit that supervises the full bare-metal stack
(gateway + adapter + UI) via supervisord-style process groups, enables and
starts it, and prints status. No hardcoded paths — everything derives from
the project root and the current Python interpreter.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

SERVICE_NAME = "llm-gateway"
UNIT_DIR = Path.home() / ".config" / "systemd" / "user"


def _render_unit(project_root: Path, python: str) -> str:
    """Render the systemd unit. Paths come from arguments, never hardcoded."""
    root = str(project_root)
    return f"""\
# llm-gateway systemd user unit — generated by wizard/install_linux.py
[Unit]
Description=LLM Gateway (gateway + adapter + UI)
After=network-online.target postgresql.service redis.service
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory={root}
EnvironmentFile={root}/.env
# Boot order safety net: gateway/main.py polls Postgres+Redis before launching
# LiteLLM (plan Issue 2). Adapter and UI are supervised alongside via the
# compose/supervisord entrypoint; for bare metal we chain them with a shell.
ExecStart={python} -c "import subprocess, sys, os; \
procs=[subprocess.Popen([sys.executable, '-u', '-m', m], cwd={root!r}, env=os.environ) for m in ['gateway.main', 'adapter.server', 'ui.app']]; \
raise SystemExit(int(any(p.wait() != 0 for p in procs)))"
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
"""


def install(project_root: Path | None = None) -> None:
    root = Path(project_root) if project_root else Path(__file__).resolve().parents[1]
    python = sys.executable

    unit_dir = UNIT_DIR
    unit_dir.mkdir(parents=True, exist_ok=True)
    unit_path = unit_dir / f"{SERVICE_NAME}.service"
    unit_path.write_text(_render_unit(root, python))

    subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
    subprocess.run(["systemctl", "--user", "enable", "--now", f"{SERVICE_NAME}.service"], check=False)
    status()
    print(f"\nUnit written to {unit_path}")
    print("Logs: journalctl --user -u llm-gateway -f")


def uninstall() -> None:
    subprocess.run(["systemctl", "--user", "disable", "--now", f"{SERVICE_NAME}.service"], check=False)
    unit_path = UNIT_DIR / f"{SERVICE_NAME}.service"
    if unit_path.exists():
        unit_path.unlink()
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
    print("Service removed.")


def status() -> None:
    if shutil.which("systemctl") is None:
        print("systemctl not found on PATH; cannot show status.")
        return
    subprocess.run(["systemctl", "--user", "status", f"{SERVICE_NAME}.service", "--no-pager"], check=False)


if __name__ == "__main__":
    install()
